// packages/web/src/components/ui/label.tsx
/**
 * components/ui/label.tsx — shadcn/ui Label（基于 @radix-ui/react-label）
 */

import * as React from 'react';
import * as LabelPrimitive from '@radix-ui/react-label';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '@/lib/utils';

const labelVariants = cva(
  'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
);

const Label = React.forwardRef<
  React.ElementRef<typeof LabelPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof LabelPrimitive.Root> &
    VariantProps<typeof labelVariants>
>(({ className, ...props }, ref) => (
  <LabelPrimitive.Root
    ref={ref}
    className={cn(labelVariants(), className)}
    {...props}
  />
));
Label.displayName = LabelPrimitive.Root.displayName;

export { Label };

// web/src/components/ui/label/Label.vue
<script setup lang="ts">
/**
 * ui/label — 表单标签（基于 reka-ui Label，类名与 React 版一致）
 */
import { Label } from 'reka-ui';
import { cn } from '@/lib/utils';

const props = defineProps<{
  for?: string;
  class?: string;
}>();
</script>

<template>
  <Label
    :for="props.for"
    :class="cn(
      'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
      props.class,
    )"
  >
    <slot />
  </Label>
</template>
