// web/src/features/security-trade/security-trade-list.tsx
/**
 * features/security-trade/security-trade-list.tsx — 证券买卖明细流水表格
 *
 * PRD §7.2【C】：列表 + 筛选（标的/日期/方向）+ 编辑/删除。
 * 交易响应不含标的名称，由 securities 列表映射展示。
 */

import { useState } from 'react';
import { ChevronLeft, ChevronRight, Pencil, Trash2, Loader2 } from 'lucide-react';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Skeleton } from '@/components/ui/skeleton';
import { useSecurityTrades, useDeleteSecurityTrade } from '@/hooks/use-security-trades';
import { useSecurities } from '@/hooks/use-securities';
import { SecurityTradeForm } from './security-trade-form';
import { formatCurrency, formatDate } from '@/lib/utils';
import { SecuritySide } from '@/lib/types';
import type {
  SecurityTradeQuery,
  SecurityTradeResponse,
} from '@/api/types';

/**
 * 外部筛选条件的就绪状态。
 *
 * 背景（缺陷4 二次修复）：本组件的标的过滤完全依赖调用方传入的 `query.securityId`。
 * 若调用方把「类型筛选没命中任何标的」或「标的字典尚未加载」错误地表达成
 * 「不传 securityId」，后端就会返回**全部**记录，用户看到的现象是「筛选器无效」。
 * 因此把这两种非常规状态显式建模，由本组件短路处理，禁止退化成无条件查询。
 *
 * - `ready`：筛选条件已确定，按 `query` 正常查询
 * - `loading`：外部依赖（如标的字典）仍在加载，展示骨架且**不发查询**
 * - `empty`：筛选条件已确定且无任何匹配标的，展示空态且**不发查询**
 */
export type TradeFilterState = 'ready' | 'loading' | 'empty';

export interface SecurityTradeListProps {
  portfolioId: string;
  /** 查询参数（标的/日期范围；分页在组件内维护） */
  query?: SecurityTradeQuery;
  /** 方向筛选（'all' | 'BUY_SEC' | 'SELL_SEC'；后端按 side 参数过滤） */
  sideFilter?: string;
  /** 外部筛选就绪状态（默认 'ready'），见 {@link TradeFilterState} */
  filterState?: TradeFilterState;
  className?: string;
  emptyText?: string;
  /** filterState==='empty' 时的空态文案（默认与 emptyText 一致） */
  filteredEmptyText?: string;
}

const PAGE_SIZE = 20;

export function SecurityTradeList({
  portfolioId,
  query,
  sideFilter = 'all',
  filterState = 'ready',
  className,
  emptyText = '暂无买卖流水',
  filteredEmptyText,
}: SecurityTradeListProps): JSX.Element {
  const [page, setPage] = useState(1);
  const [editing, setEditing] = useState<SecurityTradeResponse | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);

  // filterState !== 'ready' 时传 null 关闭查询（useSecurityTrades 内部 enabled: Boolean(portfolioId)），
  // 避免「筛选无匹配 / 字典未就绪」被后端理解为「无筛选条件」而返回全量数据。
  const queryEnabled = filterState === 'ready';
  const {
    data,
    isLoading: tradesLoading,
    isError,
  } = useSecurityTrades(queryEnabled ? portfolioId : null, {
    ...query,
    ...(sideFilter !== 'all' ? { side: sideFilter as SecuritySide } : {}),
    page,
    pageSize: PAGE_SIZE,
  });
  const deleteMutation = useDeleteSecurityTrade();
  const { data: securities = [] } = useSecurities(portfolioId);

  const isLoading = filterState === 'loading' || tradesLoading;
  const resolvedEmptyText =
    filterState === 'empty' ? (filteredEmptyText ?? emptyText) : emptyText;

  const securityMap = new Map(securities.map((s) => [s.id, s]));
  const items = queryEnabled ? (data?.items ?? []) : [];
  const total = queryEnabled ? (data?.total ?? 0) : 0;
  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));

  /** 当前页统计：买入金额（含费成交额）/ 卖出金额（含费成交额）/ 累计费用合计 */
  const buyAmount = items
    .filter((t) => t.side === SecuritySide.BUY_SEC)
    .reduce((sum, t) => sum + Number(t.quantity) * Number(t.costPrice), 0);
  const sellAmount = items
    .filter((t) => t.side === SecuritySide.SELL_SEC)
    .reduce((sum, t) => sum + Number(t.quantity) * Number(t.costPrice), 0);
  const totalFee = items.reduce((sum, t) => sum + Number(t.feeTotal), 0);

  const handleConfirmDelete = () => {
    if (deletingId) {
      deleteMutation.mutate(
        { portfolioId, id: deletingId },
        { onSettled: () => setDeletingId(null) },
      );
    }
  };

  return (
    <div className={className}>
      {isLoading ? (
        <div className="space-y-2">
          {[1, 2, 3, 4, 5].map((i) => (
            <Skeleton key={i} className="h-12 w-full" />
          ))}
        </div>
      ) : isError ? (
        <div className="py-10 text-center text-sm text-muted-foreground">
          加载失败，请稍后重试
        </div>
      ) : items.length === 0 ? (
        <div className="py-10 text-center text-sm text-muted-foreground">
          {resolvedEmptyText}
        </div>
      ) : (
        <>
          <div className="mb-3 grid grid-cols-1 gap-3 sm:grid-cols-3">
            <div className="rounded-md border bg-muted/40 px-4 py-3">
              <p className="text-xs text-muted-foreground">买入金额（含费）</p>
              <p className="mt-1 font-mono text-base font-medium tabular-nums text-up">
                {formatCurrency(buyAmount)}
              </p>
            </div>
            <div className="rounded-md border bg-muted/40 px-4 py-3">
              <p className="text-xs text-muted-foreground">卖出金额（含费）</p>
              <p className="mt-1 font-mono text-base font-medium tabular-nums text-down">
                {formatCurrency(sellAmount)}
              </p>
            </div>
            <div className="rounded-md border bg-muted/40 px-4 py-3">
              <p className="text-xs text-muted-foreground">累计费用合计</p>
              <p className="mt-1 font-mono text-base font-medium tabular-nums">
                {formatCurrency(totalFee)}
              </p>
            </div>
          </div>
          <div className="overflow-x-auto">
            <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[100px]">日期</TableHead>
                <TableHead className="w-[60px]">方向</TableHead>
                <TableHead>标的</TableHead>
                <TableHead className="text-right">数量</TableHead>
                <TableHead className="text-right">成本价</TableHead>
                <TableHead className="text-right">佣金</TableHead>
                <TableHead className="text-right">印花税</TableHead>
                <TableHead className="text-right">其他</TableHead>
                <TableHead className="text-right">费用合计</TableHead>
                <TableHead className="text-right">成交额</TableHead>
                <TableHead className="w-[100px]">备注</TableHead>
                <TableHead className="w-[80px] text-right">操作</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {items.map((t) => {
                const sec = securityMap.get(t.securityId);
                const qty = Number(t.quantity);
                /** 成本价（含费单价，INC-03 由 price 重命名） */
                const costPrice = Number(t.costPrice);
                /** 成交额（含费）= 数量 × 含费单价 */
                const amount = qty * costPrice;
                return (
                  <TableRow key={t.id}>
                    <TableCell className="font-mono text-sm whitespace-nowrap">
                      {formatDate(t.date)}
                    </TableCell>
                    <TableCell>
                      <Badge
                        variant={
                          t.side === SecuritySide.BUY_SEC
                            ? 'secondary'
                            : 'outline'
                        }
                        className={
                          t.side === SecuritySide.BUY_SEC
                            ? 'bg-up-soft text-up'
                            : 'bg-down-soft text-down'
                        }
                      >
                        {t.side === SecuritySide.BUY_SEC ? '买入' : '卖出'}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-sm whitespace-nowrap">
                      {sec ? (
                        <span>
                          {sec.name}
                          <span className="ml-1 text-xs text-muted-foreground">
                            {sec.code}
                          </span>
                        </span>
                      ) : (
                        '-'
                      )}
                    </TableCell>
                    <TableCell className="text-right font-mono text-sm whitespace-nowrap">
                      {Number(t.quantity).toLocaleString('zh-CN', {
                        maximumFractionDigits: 4,
                      })}
                    </TableCell>
                    <TableCell className="text-right font-mono text-sm whitespace-nowrap">
                      {formatCurrency(t.costPrice, 6)}
                    </TableCell>
                    <TableCell className="text-right font-mono text-sm whitespace-nowrap">
                      {formatCurrency(t.commission)}
                    </TableCell>
                    <TableCell className="text-right font-mono text-sm whitespace-nowrap">
                      {formatCurrency(t.stampTax)}
                    </TableCell>
                    <TableCell className="text-right font-mono text-sm whitespace-nowrap">
                      {formatCurrency(t.other)}
                    </TableCell>
                    <TableCell className="text-right font-mono text-sm whitespace-nowrap">
                      {formatCurrency(t.feeTotal)}
                    </TableCell>
                    <TableCell className="text-right font-mono whitespace-nowrap">
                      {formatCurrency(amount)}
                    </TableCell>
                    <TableCell className="max-w-[110px] truncate text-sm text-muted-foreground">
                      {t.note || '-'}
                    </TableCell>
                    <TableCell className="text-right whitespace-nowrap">
                      <div className="flex justify-end gap-1">
                        <Button
                          size="icon"
                          variant="ghost"
                          onClick={() => setEditing(t)}
                          title="编辑"
                        >
                          <Pencil className="h-4 w-4" />
                        </Button>
                        <Button
                          size="icon"
                          variant="ghost"
                          onClick={() => setDeletingId(t.id)}
                          title="删除"
                        >
                          <Trash2 className="h-4 w-4 text-red-500" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
          </div>
        </>
      )}

      {/* 分页 */}
      {!isLoading && !isError && total > PAGE_SIZE && (
        <div className="flex items-center justify-between pt-3">
          <span className="text-xs text-muted-foreground">
            共 {total} 条 · 第 {page}/{totalPages} 页
          </span>
          <div className="flex gap-1">
            <Button
              size="sm"
              variant="outline"
              disabled={page <= 1}
              onClick={() => setPage((p) => Math.max(1, p - 1))}
            >
              <ChevronLeft className="h-4 w-4" />
              上一页
            </Button>
            <Button
              size="sm"
              variant="outline"
              disabled={page >= totalPages}
              onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
            >
              下一页
              <ChevronRight className="h-4 w-4" />
            </Button>
          </div>
        </div>
      )}

      {/* 编辑弹窗 */}
      <Dialog open={Boolean(editing)} onOpenChange={(o) => !o && setEditing(null)}>
        <DialogContent className="max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>编辑买卖流水</DialogTitle>
          </DialogHeader>
          {editing && (
            <SecurityTradeForm
              portfolioId={portfolioId}
              trade={editing}
              onSuccess={() => setEditing(null)}
            />
          )}
        </DialogContent>
      </Dialog>

      {/* 删除确认 */}
      <AlertDialog
        open={Boolean(deletingId)}
        onOpenChange={(o) => !o && setDeletingId(null)}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>确认删除该笔买卖流水？</AlertDialogTitle>
            <AlertDialogDescription>
              删除后持仓将重新推导，并从该日期起的净值与 XIRR 将被重算。此操作不可撤销。
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={deleteMutation.isPending}>
              取消
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={handleConfirmDelete}
              disabled={deleteMutation.isPending}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              {deleteMutation.isPending && (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              )}
              确认删除
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}

// web/src/modules/security-trade/components/SecurityTradeList.vue
<script setup lang="ts">
/**
 * modules/security-trade/components/SecurityTradeList.vue — 证券买卖明细流水表格
 *
 * 平移自 React 版 web/src/features/security-trade/security-trade-list.tsx。
 *
 * PRD §7.2【C】：列表 + 筛选（标的/日期/方向）+ 编辑/删除。
 * 交易响应不含标的名称，由 securities 列表字典映射展示。
 *
 * 行为契约对齐要点：
 * - 筛选三态短路（缺陷4 二次修复）：`filterState !== 'ready'` 时禁用列表查询，
 *   绝不退化成「无 securityId → 后端返回全量」导致筛选器失效；
 *   loading 显示骨架、empty 显示空态，均不发请求。
 * - 三统计块口径（INC-03）：买入金额 = Σ(BUY qty×costPrice)、卖出金额 = Σ(SELL)、
 *   累计费用 = Σ(feeTotal)，随当前可见结果集动态变化。
 * - mutation（删除）成功后由 useDeleteSecurityTrade 失效 ['security-trades'] 前缀缓存，
 *   本列表 queryKey 同前缀，自动刷新。
 */

import { computed, ref } from 'vue';
import { ChevronLeft, ChevronRight, Pencil, Trash2, Loader2 } from 'lucide-vue-next';
import { useQuery } from '@tanstack/vue-query';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import {
  AlertDialog,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogCancel,
  AlertDialogAction,
} from '@/components/ui/alert-dialog';
import { Skeleton } from '@/components/ui/skeleton';
import { listSecurityTrades } from '@/api/security-trade.api';
import { useSecurities } from '@/composables/use-securities';
import { useDeleteSecurityTrade } from '../composables/use-security-trades';
import SecurityTradeForm from './SecurityTradeForm.vue';
import type { SecurityTradeQuery, SecurityTradeResponse } from '@/api/types';
import type { TradeFilterState } from '@/modules/holdings/trade-security-filter';
import { SecuritySide } from '@/lib/types';
import { formatCurrency, formatDate } from '@/lib/utils';

const props = withDefaults(
  defineProps<{
    portfolioId: string;
    /** 查询参数（标的/日期范围；分页在组件内维护） */
    query?: SecurityTradeQuery;
    /** 方向筛选（'all' | 'BUY_SEC' | 'SELL_SEC'；后端按 side 参数过滤） */
    sideFilter?: 'all' | 'BUY_SEC' | 'SELL_SEC';
    /** 外部筛选就绪状态（默认 'ready'），见 TradeFilterState */
    filterState?: TradeFilterState;
    emptyText?: string;
    /** filterState==='empty' 时的空态文案（默认与 emptyText 一致） */
    filteredEmptyText?: string;
    class?: string;
  }>(),
  {
    sideFilter: 'all',
    filterState: 'ready',
    emptyText: '暂无买卖流水',
  },
);

const PAGE_SIZE = 20;

const page = ref(1);
const editing = ref<SecurityTradeResponse | null>(null);
const deletingId = ref<string | null>(null);

// filterState !== 'ready' 时禁用查询（短路），避免「筛选无匹配 / 字典未就绪」
// 被后端理解为「无筛选条件」而返回全量数据。
const queryEnabled = computed(() => props.filterState === 'ready');

const listQuery = computed<SecurityTradeQuery>(() => ({
  ...(props.query ?? {}),
  ...(props.sideFilter !== 'all' ? { side: props.sideFilter as SecuritySide } : {}),
  page: page.value,
  pageSize: PAGE_SIZE,
}));

const {
  data,
  isLoading: tradesLoading,
  isError,
} = useQuery({
  queryKey: computed(() => [
    'security-trades',
    'list',
    queryEnabled.value ? props.portfolioId : 'disabled',
    listQuery.value,
  ]),
  queryFn: () => listSecurityTrades(props.portfolioId, listQuery.value),
  enabled: queryEnabled,
  staleTime: 30 * 1000,
});

const { data: securitiesData } = useSecurities(props.portfolioId);
const securityMap = computed(
  () => new Map((securitiesData.value ?? []).map((s) => [s.id, s])),
);

const items = computed<SecurityTradeResponse[]>(() =>
  queryEnabled.value ? (data.value?.items ?? []) : [],
);
const total = computed(() => (queryEnabled.value ? (data.value?.total ?? 0) : 0));
const totalPages = computed(() => Math.max(1, Math.ceil(total.value / PAGE_SIZE)));

const isLoading = computed(
  () => props.filterState === 'loading' || tradesLoading.value,
);
const resolvedEmptyText = computed(() =>
  props.filterState === 'empty'
    ? (props.filteredEmptyText ?? props.emptyText)
    : props.emptyText,
);

/** 当前页统计：买入金额（含费成交额）/ 卖出金额（含费成交额）/ 累计费用合计 */
const buyAmount = computed(() =>
  items.value
    .filter((t) => t.side === SecuritySide.BUY_SEC)
    .reduce((sum, t) => sum + Number(t.quantity) * Number(t.costPrice), 0),
);
const sellAmount = computed(() =>
  items.value
    .filter((t) => t.side === SecuritySide.SELL_SEC)
    .reduce((sum, t) => sum + Number(t.quantity) * Number(t.costPrice), 0),
);
const totalFee = computed(() =>
  items.value.reduce((sum, t) => sum + Number(t.feeTotal), 0),
);

const deleteMutation = useDeleteSecurityTrade();
const isDeleting = computed(() => deleteMutation.isPending.value);
/**
 * 删除确认弹窗关闭处理。
 *
 * reka-ui AlertDialogAction（内部 DialogClose）的关闭 handler 与用户 @click 按
 * [reka, user] 顺序合并执行：reka 先 onOpenChange(false) 再跑用户 handler。
 * 故「清空 deletingId」必须延迟到微任务，否则用户确认 handler 执行时 id 已被清空，
 * 删除 mutation 拿不到参数（对齐 PortfolioManagementCard 的删除模式）。
 */
function handleDeleteDialogOpenChange(o: boolean): void {
  if (!o) {
    queueMicrotask(() => (deletingId.value = null));
  }
}

function handleConfirmDelete(): void {
  if (!deletingId.value) return;
  deleteMutation.mutate(
    { portfolioId: props.portfolioId, id: deletingId.value },
    { onSettled: () => (deletingId.value = null) },
  );
}

/** 成交额（含费）= 数量 × 含费单价 */
function amountOf(t: SecurityTradeResponse): number {
  return Number(t.quantity) * Number(t.costPrice);
}
</script>

<template>
  <div :class="props.class">
    <!-- 加载态骨架 -->
    <div v-if="isLoading" class="space-y-2">
      <Skeleton v-for="i in 5" :key="i" class="h-12 w-full" />
    </div>

    <!-- 错误态 -->
    <div
      v-else-if="isError"
      class="py-10 text-center text-sm text-muted-foreground"
    >
      加载失败，请稍后重试
    </div>

    <!-- 空态 -->
    <div
      v-else-if="items.length === 0"
      class="py-10 text-center text-sm text-muted-foreground"
    >
      {{ resolvedEmptyText }}
    </div>

    <!-- 数据态 -->
    <template v-else>
      <!-- 三统计块 -->
      <div class="mb-3 grid grid-cols-1 gap-3 sm:grid-cols-3">
        <div class="rounded-md border bg-muted/40 px-4 py-3">
          <p class="text-xs text-muted-foreground">买入金额（含费）</p>
          <p class="mt-1 font-mono text-base font-medium tabular-nums text-up">
            {{ formatCurrency(buyAmount, 2) }}
          </p>
        </div>
        <div class="rounded-md border bg-muted/40 px-4 py-3">
          <p class="text-xs text-muted-foreground">卖出金额（含费）</p>
          <p class="mt-1 font-mono text-base font-medium tabular-nums text-down">
            {{ formatCurrency(sellAmount, 2) }}
          </p>
        </div>
        <div class="rounded-md border bg-muted/40 px-4 py-3">
          <p class="text-xs text-muted-foreground">累计费用合计</p>
          <p class="mt-1 font-mono text-base font-medium tabular-nums">
            {{ formatCurrency(totalFee, 2) }}
          </p>
        </div>
      </div>

      <!-- 流水表 -->
      <div class="overflow-x-auto">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead class="w-[100px]">日期</TableHead>
              <TableHead class="w-[60px]">方向</TableHead>
              <TableHead>标的</TableHead>
              <TableHead class="text-right">数量</TableHead>
              <TableHead class="text-right">成本价</TableHead>
              <TableHead class="text-right">佣金</TableHead>
              <TableHead class="text-right">印花税</TableHead>
              <TableHead class="text-right">其他</TableHead>
              <TableHead class="text-right">费用合计</TableHead>
              <TableHead class="text-right">成交额</TableHead>
              <TableHead class="w-[100px]">备注</TableHead>
              <TableHead class="w-[80px] text-right">操作</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow v-for="t in items" :key="t.id">
              <TableCell class="font-mono text-sm whitespace-nowrap">
                {{ formatDate(t.date) }}
              </TableCell>
              <TableCell>
                <Badge
                  v-if="t.side === SecuritySide.BUY_SEC"
                  variant="secondary"
                  class="bg-up-soft text-up"
                >
                  买入
                </Badge>
                <Badge v-else variant="outline" class="bg-down-soft text-down">
                  卖出
                </Badge>
              </TableCell>
              <TableCell class="text-sm whitespace-nowrap">
                <span v-if="securityMap.get(t.securityId)">
                  {{ securityMap.get(t.securityId)!.name }}
                  <span class="ml-1 text-xs text-muted-foreground">
                    {{ securityMap.get(t.securityId)!.code }}
                  </span>
                </span>
                <span v-else>-</span>
              </TableCell>
              <TableCell class="text-right font-mono text-sm whitespace-nowrap">
                {{ Number(t.quantity).toLocaleString('zh-CN', { maximumFractionDigits: 4 }) }}
              </TableCell>
              <TableCell class="text-right font-mono text-sm whitespace-nowrap">
                {{ formatCurrency(t.costPrice, 6) }}
              </TableCell>
              <TableCell class="text-right font-mono text-sm whitespace-nowrap">
                {{ formatCurrency(t.commission, 2) }}
              </TableCell>
              <TableCell class="text-right font-mono text-sm whitespace-nowrap">
                {{ formatCurrency(t.stampTax, 2) }}
              </TableCell>
              <TableCell class="text-right font-mono text-sm whitespace-nowrap">
                {{ formatCurrency(t.other, 2) }}
              </TableCell>
              <TableCell class="text-right font-mono text-sm whitespace-nowrap">
                {{ formatCurrency(t.feeTotal, 2) }}
              </TableCell>
              <TableCell class="text-right font-mono whitespace-nowrap">
                {{ formatCurrency(amountOf(t), 2) }}
              </TableCell>
              <TableCell class="max-w-[110px] truncate text-sm text-muted-foreground">
                {{ t.note || '-' }}
              </TableCell>
              <TableCell class="text-right whitespace-nowrap">
                <div class="flex justify-end gap-1">
                  <Button
                    size="icon"
                    variant="ghost"
                    title="编辑"
                    @click="editing = t"
                  >
                    <Pencil class="h-4 w-4" />
                  </Button>
                  <Button
                    size="icon"
                    variant="ghost"
                    title="删除"
                    @click="deletingId = t.id"
                  >
                    <Trash2 class="h-4 w-4 text-red-500" />
                  </Button>
                </div>
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>

      <!-- 分页 -->
      <div
        v-if="total > PAGE_SIZE"
        class="flex items-center justify-between pt-3"
      >
        <span class="text-xs text-muted-foreground">
          共 {{ total }} 条 · 第 {{ page }}/{{ totalPages }} 页
        </span>
        <div class="flex gap-1">
          <Button
            size="sm"
            variant="outline"
            :disabled="page <= 1"
            @click="page = Math.max(1, page - 1)"
          >
            <ChevronLeft class="h-4 w-4" />
            上一页
          </Button>
          <Button
            size="sm"
            variant="outline"
            :disabled="page >= totalPages"
            @click="page = Math.min(totalPages, page + 1)"
          >
            下一页
            <ChevronRight class="h-4 w-4" />
          </Button>
        </div>
      </div>
    </template>

    <!-- 编辑弹窗 -->
    <Dialog :open="Boolean(editing)" @update:open="(o) => !o && (editing = null)">
      <DialogContent class="max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>编辑买卖流水</DialogTitle>
        </DialogHeader>
        <SecurityTradeForm
          :portfolio-id="props.portfolioId"
          :trade="editing"
          @success="editing = null"
        />
      </DialogContent>
    </Dialog>

    <!-- 删除确认 -->
    <AlertDialog
      :open="Boolean(deletingId)"
      @update:open="handleDeleteDialogOpenChange"
    >
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>确认删除该笔买卖流水？</AlertDialogTitle>
          <AlertDialogDescription>
            删除后持仓将重新推导，并从该日期起的净值与 XIRR 将被重算。此操作不可撤销。
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel :disabled="isDeleting">取消</AlertDialogCancel>
          <AlertDialogAction
            class="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            :disabled="isDeleting"
            @click="handleConfirmDelete"
          >
            <Loader2 v-if="isDeleting" class="mr-2 h-4 w-4 animate-spin" />
            确认删除
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  </div>
</template>
