// web/src/features/admin/quote-provider-dialog.tsx
/**
 * features/admin/quote-provider-dialog.tsx — 数据来源（提供方）新增/编辑对话框
 *
 * 字段：name、access_method（Select）、base_url | sdk_name（按接入方式二选一）、
 * description、enabled（唯一开关）。
 * 全局单一活跃源（is_default/is_active）已移除（ADR-002 方案 X），提供方仅保留启用/停用开关。
 *
 * 风格对齐同模块其它对话框（QuoteInterfaceDialog / InterfaceCategoryDialog）：
 * - 独立 *-dialog.tsx 组件，props 为 { open, onOpenChange, editing }；
 * - 表单状态由对话框内部持有，以 toForm(editing) + useEffect 在每次打开时重置；
 * - 接入方式使用 shadcn Select（与 QuoteInterfaceDialog 的 HTTP 方法一致）；
 * - 提交后 onOpenChange(false) 关闭并就地刷新列表（由 hooks 失效缓存）。
 */

import { useEffect, useState } from 'react';
import { Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { toast } from 'sonner';
import type { QuoteProvider, QuoteProviderAccessMethod } from '@/api/quote-provider.api';
import { useCreateQuoteProvider, useQuoteProviders, useUpdateQuoteProvider } from '@/hooks/use-quote-provider';

interface FormState {
  name: string;
  accessMethod: QuoteProviderAccessMethod;
  baseUrl: string;
  sdkName: string;
  description: string;
  enabled: boolean;
}

function toForm(edit: QuoteProvider | null): FormState {
  if (!edit) {
    return {
      name: '',
      accessMethod: 'https',
      baseUrl: '',
      sdkName: '',
      description: '',
      enabled: true,
    };
  }
  return {
    name: edit.name,
    accessMethod: edit.access_method,
    baseUrl: (edit.config?.base_url as string) ?? '',
    sdkName: (edit.config?.sdk_name as string) ?? '',
    description: edit.description ?? '',
    enabled: edit.enabled,
  };
}

export interface QuoteProviderDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  editing: QuoteProvider | null;
}

export function QuoteProviderDialog({
  open,
  onOpenChange,
  editing,
}: QuoteProviderDialogProps): JSX.Element {
  const createMut = useCreateQuoteProvider();
  const updateMut = useUpdateQuoteProvider();
  const { data: providers } = useQuoteProviders();
  const [form, setForm] = useState<FormState>(() => toForm(editing));
  const [nameError, setNameError] = useState<string | null>(null);

  useEffect(() => {
    if (open) {
      setForm(toForm(editing));
      setNameError(null);
    }
  }, [open, editing]);

  const pending = createMut.isPending || updateMut.isPending;

  const handleSubmit = (): void => {
    const name = form.name.trim();
    if (!name) {
      toast.error('请填写名称');
      return;
    }
    // 名称唯一性：创建时与任一现有提供方重名、编辑时与「其它」提供方重名均拦截
    const dupName = (providers ?? []).find(
      (p) =>
        p.name.trim().toLowerCase() === name.toLowerCase() && p.id !== editing?.id,
    );
    if (dupName) {
      setNameError('已存在同名数据来源，请更换名称');
      return;
    }
    if (form.accessMethod === 'https' && !form.baseUrl.trim()) {
      toast.error('HTTPS 接入方式必须填写 API 基础地址');
      return;
    }
    if (form.accessMethod === 'sdk' && !form.sdkName.trim()) {
      toast.error('SDK 接入方式必须填写 SDK 名称');
      return;
    }
    const config =
      form.accessMethod === 'https'
        ? { base_url: form.baseUrl.trim() }
        : { sdk_name: form.sdkName.trim() };
    const payload = {
      name,
      access_method: form.accessMethod,
      config,
      enabled: form.enabled,
      description: form.description.trim() || null,
    };
    if (editing) {
      updateMut.mutate(
        { id: editing.id, body: payload },
        { onSuccess: () => onOpenChange(false) },
      );
    } else {
      createMut.mutate(payload, { onSuccess: () => onOpenChange(false) });
    }
  };

  const close = (): void => onOpenChange(false);

  return (
    <Dialog open={open} onOpenChange={(v) => (v ? onOpenChange(true) : close())}>
      <DialogContent className="max-w-xl">
        <DialogHeader>
          <DialogTitle>{editing ? '编辑数据来源' : '新增数据来源'}</DialogTitle>
          <DialogDescription>
            {editing ? '修改该数据来源的配置' : '新增一个行情数据来源（提供方）'}
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="qp-name">名称</Label>
            <Input
              id="qp-name"
              placeholder="如 新浪财经"
              value={form.name}
              aria-invalid={nameError ? true : undefined}
              onChange={(e) => {
                setNameError(null);
                setForm({ ...form, name: e.target.value });
              }}
            />
            {nameError && (
              <p className="text-xs text-red-500">{nameError}</p>
            )}
          </div>

          <div className="space-y-2">
            <Label htmlFor="qp-access-method">接入方式</Label>
            <Select
              value={form.accessMethod}
              onValueChange={(v) =>
                setForm({ ...form, accessMethod: v as QuoteProviderAccessMethod })
              }
            >
              <SelectTrigger id="qp-access-method">
                <SelectValue placeholder="选择接入方式" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="https">HTTPS（API 地址）</SelectItem>
                <SelectItem value="sdk">SDK（如 akshare）</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {form.accessMethod === 'https' ? (
            <div className="space-y-2">
              <Label htmlFor="qp-base-url">API 基础地址</Label>
              <Input
                id="qp-base-url"
                placeholder="https://example.com/api"
                value={form.baseUrl}
                onChange={(e) =>
                  setForm({ ...form, baseUrl: e.target.value })
                }
              />
            </div>
          ) : (
            <div className="space-y-2">
              <Label htmlFor="qp-sdk-name">SDK 名称</Label>
              <Input
                id="qp-sdk-name"
                placeholder="如 akshare"
                value={form.sdkName}
                onChange={(e) =>
                  setForm({ ...form, sdkName: e.target.value })
                }
              />
            </div>
          )}

          <div className="space-y-2">
            <Label htmlFor="qp-desc">描述</Label>
            <Textarea
              id="qp-desc"
              placeholder="可选，备注该数据来源用途"
              value={form.description}
              onChange={(e) =>
                setForm({ ...form, description: e.target.value })
              }
            />
          </div>

          <div className="flex items-center justify-between rounded-md border p-3">
            <div className="space-y-0.5">
              <Label htmlFor="qp-enabled" className="text-sm">
                启用
              </Label>
            <p className="text-xs text-muted-foreground">
              禁用的提供方不参与行情解析（仍可被重新启用）
            </p>
          </div>
          <Switch
            id="qp-enabled"
            checked={form.enabled}
            onCheckedChange={(v) => setForm({ ...form, enabled: v })}
          />
        </div>
      </div>

        <DialogFooter>
          <Button variant="outline" onClick={close}>
            取消
          </Button>
          <Button onClick={handleSubmit} disabled={pending}>
            {pending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            保存
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// web/src/modules/admin/components/QuoteProviderDialog.vue
<script setup lang="ts">
/**
 * modules/admin/components/QuoteProviderDialog.vue — 数据来源（提供方）新增/编辑对话框
 *
 * 平移自 React 版 features/admin/quote-provider-dialog.tsx，行为契约一致。
 * 字段：name、access_method（Select）、base_url | sdk_name（按接入方式二选一）、
 * description、enabled（唯一开关）。
 * 全局单一活跃源（is_default/is_active）已移除（ADR-002 方案 X），提供方仅保留启用/停用开关。
 */

import { reactive, ref, watch } from 'vue';
import { Loader2 } from 'lucide-vue-next';
import { toast } from '@/composables/use-toast';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import type {
  QuoteProvider,
  QuoteProviderAccessMethod,
} from '@/api/quote-provider.api';
import {
  useCreateQuoteProvider,
  useQuoteProviders,
  useUpdateQuoteProvider,
} from '../composables/use-quote-provider';

interface FormState {
  name: string;
  accessMethod: QuoteProviderAccessMethod;
  baseUrl: string;
  sdkName: string;
  description: string;
  enabled: boolean;
}

function toForm(edit: QuoteProvider | null): FormState {
  if (!edit) {
    return {
      name: '',
      accessMethod: 'https',
      baseUrl: '',
      sdkName: '',
      description: '',
      enabled: true,
    };
  }
  return {
    name: edit.name,
    accessMethod: edit.access_method,
    baseUrl: (edit.config?.base_url as string) ?? '',
    sdkName: (edit.config?.sdk_name as string) ?? '',
    description: edit.description ?? '',
    enabled: edit.enabled,
  };
}

const props = defineProps<{
  open: boolean;
  /** 传入则编辑模式，否则新增 */
  editing: QuoteProvider | null;
}>();

const emit = defineEmits<{ openChange: [open: boolean] }>();

const createMut = useCreateQuoteProvider();
const updateMut = useUpdateQuoteProvider();
const { data: providers } = useQuoteProviders();

const form = reactive<FormState>(toForm(props.editing));
const nameError = ref<string | null>(null);

// 每次打开时按传入提供方重置表单（对齐 React 版 useEffect）
watch(
  () => [props.open, props.editing] as const,
  ([open]) => {
    if (open) {
      Object.assign(form, toForm(props.editing));
      nameError.value = null;
    }
  },
  { immediate: true },
);

const pending = () => createMut.isPending.value || updateMut.isPending.value;

function handleSubmit(): void {
  const name = form.name.trim();
  if (!name) {
    toast.error('请填写名称');
    return;
  }
  // 名称唯一性：创建时与任一现有提供方重名、编辑时与「其它」提供方重名均拦截
  const dupName = (providers.value ?? []).find(
    (p) =>
      p.name.trim().toLowerCase() === name.toLowerCase() &&
      p.id !== props.editing?.id,
  );
  if (dupName) {
    nameError.value = '已存在同名数据来源，请更换名称';
    return;
  }
  if (form.accessMethod === 'https' && !form.baseUrl.trim()) {
    toast.error('HTTPS 接入方式必须填写 API 基础地址');
    return;
  }
  if (form.accessMethod === 'sdk' && !form.sdkName.trim()) {
    toast.error('SDK 接入方式必须填写 SDK 名称');
    return;
  }
  const config =
    form.accessMethod === 'https'
      ? { base_url: form.baseUrl.trim() }
      : { sdk_name: form.sdkName.trim() };
  const payload = {
    name,
    access_method: form.accessMethod,
    config,
    enabled: form.enabled,
    description: form.description.trim() || null,
  };
  if (props.editing) {
    updateMut.mutate(
      { id: props.editing.id, body: payload },
      { onSuccess: () => emit('openChange', false) },
    );
  } else {
    createMut.mutate(payload, { onSuccess: () => emit('openChange', false) });
  }
}
</script>

<template>
  <Dialog :open="props.open" @update:open="(v: boolean) => emit('openChange', v)">
    <DialogContent class="max-w-xl">
      <DialogHeader>
        <DialogTitle>{{ props.editing ? '编辑数据来源' : '新增数据来源' }}</DialogTitle>
        <DialogDescription>
          {{ props.editing ? '修改该数据来源的配置' : '新增一个行情数据来源（提供方）' }}
        </DialogDescription>
      </DialogHeader>

      <div class="space-y-4">
        <div class="space-y-2">
          <Label for="qp-name">名称</Label>
          <Input
            id="qp-name"
            v-model="form.name"
            placeholder="如 新浪财经"
            :aria-invalid="nameError ? true : undefined"
            @update:model-value="nameError = null"
          />
          <p v-if="nameError" class="text-xs text-red-500">{{ nameError }}</p>
        </div>

        <div class="space-y-2">
          <Label for="qp-access-method">接入方式</Label>
          <Select v-model="form.accessMethod">
            <SelectTrigger id="qp-access-method">
              <SelectValue placeholder="选择接入方式" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="https">HTTPS（API 地址）</SelectItem>
              <SelectItem value="sdk">SDK（如 akshare）</SelectItem>
            </SelectContent>
          </Select>
        </div>

        <div v-if="form.accessMethod === 'https'" class="space-y-2">
          <Label for="qp-base-url">API 基础地址</Label>
          <Input
            id="qp-base-url"
            v-model="form.baseUrl"
            placeholder="https://example.com/api"
          />
        </div>
        <div v-else class="space-y-2">
          <Label for="qp-sdk-name">SDK 名称</Label>
          <Input id="qp-sdk-name" v-model="form.sdkName" placeholder="如 akshare" />
        </div>

        <div class="space-y-2">
          <Label for="qp-desc">描述</Label>
          <Textarea
            id="qp-desc"
            v-model="form.description"
            placeholder="可选，备注该数据来源用途"
            :rows="3"
          />
        </div>

        <div class="flex items-center justify-between rounded-md border p-3">
          <div class="space-y-0.5">
            <Label for="qp-enabled" class="text-sm">启用</Label>
            <p class="text-xs text-muted-foreground">
              禁用的提供方不参与行情解析（仍可被重新启用）
            </p>
          </div>
          <Switch id="qp-enabled" v-model="form.enabled" />
        </div>
      </div>

      <DialogFooter>
        <Button variant="outline" @click="emit('openChange', false)">取消</Button>
        <Button :disabled="pending()" @click="handleSubmit">
          <Loader2 v-if="pending()" class="mr-2 h-4 w-4 animate-spin" />
          保存
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>
