// packages/web/src/components/charts/yearly-bar-chart.tsx
/**
 * components/charts/yearly-bar-chart.tsx — 年度收益柱状图（Recharts）
 *
 * 输入 XirrSeriesPoint[]（按年聚合），展示各年度收益率对比柱状图。
 */

import {
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { formatPercent } from '@/lib/utils';
import type { XirrSeriesPoint } from '@investment-tracker/shared';

export interface YearlyBarChartProps {
  data: XirrSeriesPoint[];
  loading?: boolean;
  title?: string;
  className?: string;
}

const POSITIVE_COLOR = 'hsl(142 71% 45%)';
const NEGATIVE_COLOR = 'hsl(0 84% 60%)';

export function YearlyBarChart({
  data,
  loading,
  title = '年度 XIRR 对比',
  className,
}: YearlyBarChartProps): JSX.Element {
  return (
    <Card className={className}>
      <CardHeader>
        <CardTitle className="text-base">{title}</CardTitle>
      </CardHeader>
      <CardContent>
        {loading ? (
          <Skeleton className="h-[260px] w-full" />
        ) : !data || data.length === 0 ? (
          <EmptyState />
        ) : (
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={data} margin={{ top: 5, right: 20, bottom: 5, left: 0 }}>
              <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
              <XAxis
                dataKey="label"
                tick={{ fontSize: 12 }}
                className="text-muted-foreground"
              />
              <YAxis
                tick={{ fontSize: 12 }}
                className="text-muted-foreground"
                tickFormatter={(v: number) => `${(v * 100).toFixed(0)}%`}
              />
              <Tooltip
                formatter={(value: number | string) => [
                  value === null || value === undefined
                    ? '数据不足'
                    : formatPercent(Number(value)),
                  'XIRR',
                ]}
                labelClassName="text-foreground"
                contentStyle={{
                  backgroundColor: 'hsl(var(--popover))',
                  border: '1px solid hsl(var(--border))',
                  borderRadius: '6px',
                  color: 'hsl(var(--popover-foreground))',
                }}
              />
              <Bar dataKey="xirrValue" name="XIRR" radius={[4, 4, 0, 0]}>
                {data.map((entry, idx) => {
                  const v = entry.xirrValue;
                  const color = v === null ? 'hsl(var(--muted-foreground))' : v >= 0 ? POSITIVE_COLOR : NEGATIVE_COLOR;
                  return <Cell key={`cell-${idx}`} fill={color} />;
                })}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        )}
      </CardContent>
    </Card>
  );
}

function EmptyState(): JSX.Element {
  return (
    <div className="flex h-[260px] items-center justify-center text-sm text-muted-foreground">
      暂无数据
    </div>
  );
}

// web/src/components/charts/YearlyBarChart.vue
<script setup lang="ts">
/**
 * components/charts/YearlyBarChart.vue — 年度收益柱状图
 *
 * 平移自 React 版 web/src/components/charts/yearly-bar-chart.tsx。
 * option 构造见 ./yearly-bar-chart（纯函数，供单测）。
 * 对外契约（props / 默认 title）与 React 版完全一致。
 */

import { computed } from 'vue';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import BaseChart from '@/components/charts/BaseChart.vue';
import { buildYearlyBarOption } from './yearly-bar-chart';
import { useChartTheme } from '@/lib/chart-theme';
import type { XirrSeriesPoint } from '@/lib/types';

const props = withDefaults(
  defineProps<{
    data: XirrSeriesPoint[];
    loading?: boolean;
    title?: string;
    class?: string;
    /** DASH-P1-05 验收 2：高亮当年柱（加深填充色形成视觉强调） */
    highlightCurrentYear?: boolean;
    /** 高亮目标年份（默认系统当前年） */
    currentYear?: number;
  }>(),
  { title: '年度 XIRR 对比', highlightCurrentYear: false },
);

const chartTheme = useChartTheme();
const option = computed(() =>
  buildYearlyBarOption({
    data: props.data,
    highlightCurrentYear: props.highlightCurrentYear,
    currentYear: props.currentYear,
    theme: chartTheme.value,
  }),
);
</script>

<template>
  <Card :class="props.class">
    <CardHeader>
      <CardTitle class="text-base">{{ props.title }}</CardTitle>
    </CardHeader>
    <CardContent>
      <Skeleton v-if="props.loading" class="h-[260px] w-full" />
      <div
        v-else-if="!props.data || props.data.length === 0"
        class="flex h-[260px] items-center justify-center text-sm text-muted-foreground"
      >
        暂无数据
      </div>
      <BaseChart v-else :option="option" :height="260" />
    </CardContent>
  </Card>
</template>
