// web/src/components/charts/NavTrendChart.vue
<script setup lang="ts">
/**
 * components/charts/NavTrendChart.vue — 累计净值 + 当年净值双线对比图
 *
 * 平移自 React 版 web/src/components/charts/nav-trend-chart.tsx。
 * option 构造见 ./nav-trend-chart（纯函数，供单测）。
 * 对外契约（props / 默认 title）与 React 版完全一致。
 *
 * BaseChart 内部 notMerge 默认开启：切换 metric 时整体替换 option，
 * 避免「第二次点击显示全部曲线」的旧 series 残留问题。
 */

import { computed } from 'vue';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import BaseChart from '@/components/charts/BaseChart.vue';
import { buildNavTrendOption } from './nav-trend-chart';
import { useChartTheme } from '@/lib/chart-theme';
import { NavMetric } from '@/lib/types';
import type { NavMetric as NavMetricType, NavSeriesPoint } from '@/lib/types';

const props = withDefaults(
  defineProps<{
    data: NavSeriesPoint[];
    loading?: boolean;
    title?: string;
    class?: string;
    /**
     * null 数据点是否连线。
     * 默认 true（历史行为，保持测试契约）；PRD §7.5 要求断线时传 false。
     */
    connectNulls?: boolean;
    /** 渲染哪些指标系列（问题④）：'cumulative' / 'year' 只注册所选 series，'both' 双线对比 */
    metric?: NavMetricType;
  }>(),
  { title: '净值趋势', connectNulls: true, metric: NavMetric.BOTH },
);

const chartTheme = useChartTheme();
const option = computed(() =>
  buildNavTrendOption({
    data: props.data,
    connectNulls: props.connectNulls,
    metric: props.metric,
    theme: chartTheme.value,
  }),
);

/** P3-1：读屏数据摘要（sr-only），用最新累计/当年净值 */
const chartSummary = computed(() => {
  const latest = props.data[props.data.length - 1];
  if (!latest) return `${props.title}：暂无数据`;
  return `${props.title}：截至 ${latest.date}，累计净值 ${latest.cumulativeNav?.toFixed(4) ?? '-'}，当年净值 ${latest.yearNav?.toFixed(4) ?? '-'}`;
});
</script>

<template>
  <Card :class="props.class">
    <CardHeader>
      <CardTitle class="text-base">{{ props.title }}</CardTitle>
    </CardHeader>
    <CardContent>
      <Skeleton v-if="props.loading" class="h-[260px] w-full" />
      <div
        v-else-if="!props.data || props.data.length === 0"
        class="flex h-[260px] items-center justify-center text-sm text-muted-foreground"
      >
        暂无数据
      </div>
      <BaseChart
        v-else
        :option="option"
        :height="260"
        :aria-label="props.title"
        :summary="chartSummary"
      />
    </CardContent>
  </Card>
</template>

// packages/web/src/components/charts/nav-trend-chart.tsx
/**
 * components/charts/nav-trend-chart.tsx — 累计净值 + 当年净值双线对比图（Recharts）
 */

import {
  CartesianGrid,
  Legend,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { formatDecimal } from '@/lib/utils';
import type { NavSeriesPoint } from '@investment-tracker/shared';

export interface NavTrendChartProps {
  data: NavSeriesPoint[];
  loading?: boolean;
  title?: string;
  className?: string;
}

export function NavTrendChart({
  data,
  loading,
  title = '净值趋势',
  className,
}: NavTrendChartProps): JSX.Element {
  return (
    <Card className={className}>
      <CardHeader>
        <CardTitle className="text-base">{title}</CardTitle>
      </CardHeader>
      <CardContent>
        {loading ? (
          <Skeleton className="h-[260px] w-full" />
        ) : !data || data.length === 0 ? (
          <EmptyState />
        ) : (
          <ResponsiveContainer width="100%" height={260}>
            <LineChart data={data} margin={{ top: 5, right: 20, bottom: 5, left: 0 }}>
              <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
              <XAxis
                dataKey="label"
                tick={{ fontSize: 12 }}
                className="text-muted-foreground"
              />
              <YAxis
                tick={{ fontSize: 12 }}
                className="text-muted-foreground"
                tickFormatter={(v: number) => v.toFixed(2)}
              />
              <Tooltip
                formatter={(value: number | string, name: string) => {
                  if (value === null || value === undefined) return ['数据不足', name];
                  if (name === '累计净值' || name === '当年净值') {
                    return [formatDecimal(Number(value), 4), name];
                  }
                  return [String(value), name];
                }}
                labelClassName="text-foreground"
                contentStyle={{
                  backgroundColor: 'hsl(var(--popover))',
                  border: '1px solid hsl(var(--border))',
                  borderRadius: '6px',
                  color: 'hsl(var(--popover-foreground))',
                }}
              />
              <Legend wrapperStyle={{ fontSize: 12 }} />
              <Line
                type="monotone"
                dataKey="cumulativeNav"
                stroke="hsl(217 91% 60%)"
                strokeWidth={2}
                dot={false}
                activeDot={{ r: 4 }}
                connectNulls
                name="累计净值"
              />
              <Line
                type="monotone"
                dataKey="yearNav"
                stroke="hsl(142 71% 45%)"
                strokeWidth={2}
                dot={false}
                activeDot={{ r: 4 }}
                connectNulls
                name="当年净值"
              />
            </LineChart>
          </ResponsiveContainer>
        )}
      </CardContent>
    </Card>
  );
}

function EmptyState(): JSX.Element {
  return (
    <div className="flex h-[260px] items-center justify-center text-sm text-muted-foreground">
      暂无数据
    </div>
  );
}
